In [27]:
import pandas as pd
import numpy as np
import re
import zipfile
import pylab as plt    
import seaborn as sns
import sys
from datetime import datetime, time
from jupyterthemes import jtplot
jtplot.style()

from functions import *

pd.set_option('display.max_columns', None)  # me muestre todas las columnas

In [51]:
shark=pd.read_csv('../data/sharkattack_parte3.csv')

Una vez que ya esta limpia la tabla de valores nulos e inconsistentes, el siguiente paso es analizarla para encontrar la mejor manera de poder obtener información relevante para el objetivo que me he impuesto.
El objetivo es relacionar las cinco especies de tiburones con mayor cantidad de ataques, con la actividad que estaban realizando los atacados y con las fechas en las que se producen, para así poder establecer un periodo anual en el eque incrementar la seguridad mientras se realizan las diferentes actividades.

Para ello, las principales columnas que voy a necesitar son las de date, year, hora, minute, activity, sex, fatal y species.

In [52]:
shark.head()

,casenumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal,species,investigator,pdf,href,href1,casenumber1,casenumber2,originalorder,unnamed,unnamed1,time,date1,hora,minutos
0,2018.06.25,25-Jun-2018,2018,Boating,usa,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303,0,0,18:00:00,25-Jun-2018,18,0
1,2018.06.18,18-Jun-2018,2018,Unprovoked,usa,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,unknown shark,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302,0,0,14:00:00,18-Jun-2018,14,0
2,2018.06.09,09-Jun-2018,2018,Invalid,usa,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,unknown shark,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301,0,0,07:45:00,09-Jun-2018,7,45
3,2018.06.08,08-Jun-2018,2018,Unprovoked,australia,New South Wales,Arrawarra Headland,Surfing,male,M,-1,Minor injury to lower leg,N,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300,0,0,00:01:00,08-Jun-2018,25,0
4,2018.06.04,04-Jun-2018,2018,Provoked,mexico,Colima,La Ticla,Free diving,Gustavo Ramos,M,-1,Lacerations to leg & hand shark PROVOKED INCIDENT,N,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299,0,0,00:01:00,04-Jun-2018,25,0

---

# Date

In [53]:
shark.date[:25]

0     25-Jun-2018
1     18-Jun-2018
2     09-Jun-2018
3     08-Jun-2018
4     04-Jun-2018
5     03-Jun-2018
6     03-Jun-2018
7     27-May-2018
8     26-May-2018
9     26-May-2018
10    24-May-2018
11    21-May-2018
12    13-May-2018
13    13-May-2018
14           2018
15    12-May-2018
16    09-May-2018
17    30-Apr-2018
18    28-Apr-2018
19    28-Apr-2018
20    25-Apr-2018
21    25-Apr-2018
22    24-Apr-2018
23    23-Apr-2018
24    22-Apr-2018
Name: date, dtype: object

In [54]:
meses_dict = {'Ene': 1,'Jan': 1, 'Feb': 2, 'Mar': 3, 'Abr': 4, 'Apr': 4, 'May': 5, 'Jun': 6, 'Jul': 7, 'Ago': 8,'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dic': 12,'Dec': 12,}
shark['mes'] = shark['date'].replace(meses_dict, regex=True)

In [55]:
shark.head()

,casenumber,date,year,type,country,area,location,activity,name,sex,age,injury,fatal,species,investigator,pdf,href,href1,casenumber1,casenumber2,originalorder,unnamed,unnamed1,time,date1,hora,minutos,mes
0,2018.06.25,25-Jun-2018,2018,Boating,usa,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303,0,0,18:00:00,25-Jun-2018,18,0,6
1,2018.06.18,18-Jun-2018,2018,Unprovoked,usa,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,unknown shark,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302,0,0,14:00:00,18-Jun-2018,14,0,6
2,2018.06.09,09-Jun-2018,2018,Invalid,usa,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,unknown shark,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301,0,0,07:45:00,09-Jun-2018,7,45,6
3,2018.06.08,08-Jun-2018,2018,Unprovoked,australia,New South Wales,Arrawarra Headland,Surfing,male,M,-1,Minor injury to lower leg,N,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300,0,0,00:01:00,08-Jun-2018,25,0,6
4,2018.06.04,04-Jun-2018,2018,Provoked,mexico,Colima,La Ticla,Free diving,Gustavo Ramos,M,-1,Lacerations to leg & hand shark PROVOKED INCIDENT,N,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299,0,0,00:01:00,04-Jun-2018,25,0,6

In [56]:
shark['mes'].apply(type).value_counts()

mes
<class 'int'>    5737
<class 'str'>     565
Name: count, dtype: int64

In [57]:
shark.loc[shark['mes'].apply(lambda x: isinstance(x, str)), 'mes'].unique()

array(['2018', '2017', '2015', '2014', '2013', '2012', '2011', '2010',
       '2009', '2008', '2006', '2004', '2001', '2000', '1999', '1998',
       '1996', '1995', '1994', '1993', '1992', '1991', '1990', '1989',
       '1988', '1987', '1986', '1985', '1984', '1983', '1982', '1981',
       '1980', '1979', '1978', '1976', '1975', '1974', '1973', '1972',
       '1971', '1970', '1969', '1968', '1966', '1965', '1964', '1963',
       '1962', '1961', '1960', '2176', '1959', '1958', '1957', '1956',
       '1955', '1954', '1953', '1952', '1951', '1950', '1949', '1948',
       '1946', '1945', '1944', '1943', '1942', '1941', '1940', '1939',
       '1938', '1937', '1936', '1932', '1931', '1930', '1929', '1928',
       '1927', '1926', '1925', '1923', '1922', '1920', '1919', '1918',
       '1917', '1915', '1914', '1913', '1912', '1911', '1910', '1909',
       '1907', '1906', '1905', '1904', '1903', '1901', '1900', '1899',
       '1898', '1897', '1896', '1895', '1893', '1892', '1890', '1888',
       '1887', '1886', '1883', '1882', '1881', '1880', '1879', '1878',
       '1876', '01-mid-1870', '1874', '1872', '1871', '1870', '1868',
       '1867', '1865', '1864', '1863', '1862', '1858', '1855', '1853',
       '1852', '1851', '1850', '1847', '1845', '1844', '1842', '1839',
       '1837', '1836', '1829', '1828', '1827', '1820', '1825', '1816',
       '1815', '1812', '1806', '1803', '1802', '1800', '1797', '1791',
       '1779', '1776', '1767', '1764', '1758', '1749', '1755', '1748',
       '1733', '1723', '1721', '1700', '1600', '1638', '1637', '1617',
       '1642', '1595', '1555', '1554', '1543', '2016', '1934', '1916',
       '1908', '2003', '1902', '1921'], dtype=object)

In [58]:
shark.date1.isna().sum()

7

In [59]:
shark.mes.value_counts()

mes
7       662
8       598
9       556
1       528
6       497
       ...
1928      1
2013      1
1976      1
1865      1
1868      1
Name: count, Length: 199, dtype: int64

In [60]:
meses = [1,2,3,4,5,6,7,8,9,10,11,12]
for i, valor in enumerate(shark['mes']):
    if valor not in meses:
        shark.at[i, 'mes'] = 0

In [61]:
shark.mes.value_counts()

mes
7     662
8     598
0     565
9     556
1     528
6     497
4     451
10    444
12    436
3     412
11    407
2     380
5     366
Name: count, dtype: int64

---

Una vez que tengo los meses, el siguiente paso es establecer el año, para ello voy a revisar la columna de year

In [ ]:
shark['mes'] = shark['date'].replace('01-mid-1870', 6)

---

# Investigator

In [ ]:
shark.investigator[:20]

In [ ]:
shark['investigator1'] = shark['investigator'].str.extract(r'^(.*?),')

In [ ]:
shark.investigator1[:20]

In [ ]:
shark.investigator.isna().sum(), shark.investigator1.isna().sum()

In [ ]:
shark.loc[shark['investigator1'].isna(), 'investigator'].values[:20]

In [ ]:
shark.pdf[:50], shark.investigator[:50]